import type { Activity, ActivityCategory } from "@/lib/types";

export const activityCategories: ActivityCategory[] = [
  "Grupos terapéuticos",
  "Grupos para el bienestar",
  "Talleres saludables",
  "Arte y salud",
  "Juecharlas",
  "Deporte y bienestar",
  "Saberes compartidos",
  "Espacios de socialización",
];

export const activities: Activity[] = [
  {
    id: "act-1",
    title: "Grupo terapéutico — Gestión emocional",
    category: "Grupos terapéuticos",
    date: "11 jun 2026",
    professional: "Laura Sánchez",
    participants: 10,
    maxParticipants: 12,
    objective: "Desarrollar herramientas de regulación emocional en grupo",
    attendance: "pendiente",
    notes: "Primera sesión del ciclo de verano",
  },
  {
    id: "act-2",
    title: "Yoga terapéutico matinal",
    category: "Grupos para el bienestar",
    date: "12 jun 2026",
    professional: "Sofía Herrera",
    participants: 14,
    maxParticipants: 16,
    objective: "Conectar respiración, movimiento y calma interior",
    attendance: "pendiente",
    notes: "Traer esterilla. Material AFDA disponible",
  },
  {
    id: "act-3",
    title: "Taller — Alimentación consciente",
    category: "Talleres saludables",
    date: "11 jun 2026",
    professional: "Carmen Ortega",
    participants: 8,
    maxParticipants: 10,
    objective: "Explorar la relación con la comida desde el autocuidado",
    attendance: "pendiente",
    notes: "Incluye degustación saludable",
  },
  {
    id: "act-4",
    title: "Arte y salud — Pintura expresiva",
    category: "Arte y salud",
    date: "13 jun 2026",
    professional: "Carmen Ortega",
    participants: 9,
    maxParticipants: 12,
    objective: "Expresar emociones a través del arte visual",
    attendance: "pendiente",
    notes: "Materiales incluidos en la actividad",
  },
  {
    id: "act-5",
    title: "Juecharla — Cuidar desde la comunidad",
    category: "Juecharlas",
    date: "10 jun 2026",
    professional: "Ana Belén Torres",
    participants: 18,
    maxParticipants: 25,
    objective: "Reflexionar sobre redes de apoyo mutuo",
    attendance: "completa",
    notes: "Buena participación y clima de confianza",
  },
  {
    id: "act-6",
    title: "Natación terapéutica",
    category: "Deporte y bienestar",
    date: "11 jun 2026",
    professional: "Sofía Herrera",
    participants: 6,
    maxParticipants: 8,
    objective: "Mejorar bienestar físico y regulación del estrés",
    attendance: "parcial",
    notes: "Actividad externa en piscina municipal",
  },
  {
    id: "act-7",
    title: "Saberes Compartidos — Gestión del estrés",
    category: "Saberes compartidos",
    date: "8 jun 2026",
    professional: "Javier Molina",
    participants: 22,
    maxParticipants: 22,
    objective: "Intercambiar estrategias de afrontamiento entre participantes",
    attendance: "completa",
    notes: "XVI convocatoria. Lista de espera activa",
  },
  {
    id: "act-8",
    title: "Café compartido — Espacio de socialización",
    category: "Espacios de socialización",
    date: "13 jun 2026",
    professional: "Javier Molina",
    participants: 15,
    maxParticipants: 20,
    objective: "Fomentar vínculos y participación social en un entorno acogedor",
    attendance: "pendiente",
    notes: "Sin inscripción previa. Aforo limitado",
  },
  {
    id: "act-9",
    title: "Grupo terapéutico — Depresión",
    category: "Grupos terapéuticos",
    date: "9 jun 2026",
    professional: "Laura Sánchez",
    participants: 11,
    maxParticipants: 12,
    objective: "Compartir experiencias y estrategias de afrontamiento",
    attendance: "completa",
    notes: "Sesión 8 de 12 del programa",
  },
  {
    id: "act-10",
    title: "Mindfulness en la naturaleza",
    category: "Grupos para el bienestar",
    date: "7 jun 2026",
    professional: "Sofía Herrera",
    participants: 13,
    maxParticipants: 15,
    objective: "Practicar atención plena en entorno natural",
    attendance: "completa",
    notes: "Salida al Parque Grande de Zaragoza",
  },
];
