import type { AgendaItem } from "@/lib/types";

export const weekAgenda: AgendaItem[] = [
  {
    id: "ag-1",
    title: "Terapia individual",
    type: "terapia",
    professional: "Dra. Elena Martínez",
    room: "Despacho 2",
    day: "Lunes",
    time: "09:00",
    endTime: "10:00",
    status: "confirmada",
  },
  {
    id: "ag-2",
    title: "Grupo terapéutico — Depresión",
    type: "grupo",
    professional: "Laura Sánchez",
    room: "Sala Bienestar",
    day: "Lunes",
    time: "11:00",
    endTime: "12:30",
    status: "confirmada",
  },
  {
    id: "ag-3",
    title: "Neuropsicología",
    type: "terapia",
    professional: "Dr. Pablo Ruiz",
    room: "Despacho 4",
    day: "Martes",
    time: "10:00",
    endTime: "11:30",
    status: "confirmada",
  },
  {
    id: "ag-4",
    title: "Reserva — Coordinación equipo",
    type: "reserva",
    professional: "Marta Giménez",
    room: "Despacho 1",
    day: "Martes",
    time: "12:00",
    endTime: "13:00",
    status: "pendiente",
  },
  {
    id: "ag-5",
    title: "Arte y salud — Expresión creativa",
    type: "grupo",
    professional: "Carmen Ortega",
    room: "Sala Actividades",
    day: "Miércoles",
    time: "16:00",
    endTime: "18:00",
    status: "confirmada",
  },
  {
    id: "ag-6",
    title: "Terapia familiar",
    type: "terapia",
    professional: "Marta Giménez",
    room: "Despacho 1",
    day: "Miércoles",
    time: "09:30",
    endTime: "11:00",
    status: "confirmada",
  },
  {
    id: "ag-7",
    title: "Deporte y bienestar — Natación terapéutica",
    type: "grupo",
    professional: "Sofía Herrera",
    room: "Externo — Piscina",
    day: "Jueves",
    time: "08:30",
    endTime: "10:00",
    status: "confirmada",
  },
  {
    id: "ag-8",
    title: "Sesión individual — Ansiedad",
    type: "terapia",
    professional: "Dra. Elena Martínez",
    room: "Despacho 2",
    day: "Jueves",
    time: "09:00",
    endTime: "10:00",
    status: "en_curso",
  },
  {
    id: "ag-9",
    title: "Grupo terapéutico — Gestión emocional",
    type: "grupo",
    professional: "Laura Sánchez",
    room: "Sala Bienestar",
    day: "Jueves",
    time: "10:30",
    endTime: "12:00",
    status: "en_curso",
  },
  {
    id: "ag-10",
    title: "Juecharla — Bienestar comunitario",
    type: "grupo",
    professional: "Ana Belén Torres",
    room: "Sala Actividades",
    day: "Viernes",
    time: "17:00",
    endTime: "19:00",
    status: "pendiente",
  },
  {
    id: "ag-11",
    title: "Fisioterapia — Sesión individual",
    type: "terapia",
    professional: "Raúl Prieto",
    room: "Despacho 5",
    day: "Viernes",
    time: "11:00",
    endTime: "12:00",
    status: "confirmada",
  },
  {
    id: "ag-12",
    title: "Espacio de socialización — Café compartido",
    type: "grupo",
    professional: "Javier Molina",
    room: "Sala Bienestar",
    day: "Viernes",
    time: "12:30",
    endTime: "14:00",
    status: "confirmada",
  },
];
