import type {
  DashboardStats,
  PayrollDocument,
  PayrollSettings,
  SendPayslipItem,
  TrackingRecord,
  Worker,
} from "./types";

export const dashboardStats: DashboardStats = {
  monthlyStatus: "en_proceso",
  totalWorkers: 14,
  payslipsUploaded: 12,
  payslipsSent: 8,
  pendingPayslips: 4,
  errorsOrMissingEmails: 2,
  progressPercent: 67,
};

export const workers: Worker[] = [
  {
    id: "w-1",
    fullName: "Elena Martinez Lopez",
    role: "Psicologo/a",
    email: "e.martinez@asociacionafda.com",
    phone: "676 112 340",
    workCentre: "Zaragoza - Sta. Lucia",
    status: "activo",
    payrollFolder: "/nominas/2026/mayo/elena-martinez",
    lastPayslipSent: "5 jun 2026",
    notes: "Sesiones individuales y grupo terapeutico.",
    startDate: "15 mar 2020",
    contractType: "Indefinido",
  },
  {
    id: "w-2",
    fullName: "Pablo Ruiz Garcia",
    role: "Neuropsicologo/a",
    email: "p.ruiz@asociacionafda.com",
    phone: "691 443 210",
    workCentre: "Zaragoza - Sta. Lucia",
    status: "activo",
    payrollFolder: "/nominas/2026/mayo/pablo-ruiz",
    lastPayslipSent: "5 jun 2026",
    notes: "Evaluaciones neuropsicologicas.",
    startDate: "1 sep 2021",
    contractType: "Indefinido",
  },
  {
    id: "w-3",
    fullName: "Laura Sanchez Prieto",
    role: "Psicologo/a",
    email: "l.sanchez@asociacionafda.com",
    phone: "620 887 451",
    workCentre: "Huesca - Berenguer",
    status: "activo",
    payrollFolder: "/nominas/2026/mayo/laura-sanchez",
    lastPayslipSent: "4 jun 2026",
    notes: "Grupos terapeuticos en sede Huesca.",
    startDate: "10 ene 2019",
    contractType: "Indefinido",
  },
  {
    id: "w-4",
    fullName: "Carmen Ortega Vidal",
    role: "Nutricionista",
    email: "c.ortega@asociacionafda.com",
    phone: "678 220 119",
    workCentre: "Zaragoza - Sta. Lucia",
    status: "activo",
    payrollFolder: "/nominas/2026/mayo/carmen-ortega",
    lastPayslipSent: null,
    notes: "Talleres saludables y seguimiento nutricional.",
    startDate: "3 abr 2022",
    contractType: "Temporal",
  },
  {
    id: "w-5",
    fullName: "Sofia Herrera Mena",
    role: "Fisioterapeuta",
    email: "",
    phone: "654 331 902",
    workCentre: "Bulbuente",
    status: "activo",
    payrollFolder: "/nominas/2026/mayo/sofia-herrera",
    lastPayslipSent: null,
    notes: "Actividades deporte y bienestar. Email pendiente de actualizar.",
    startDate: "20 jun 2023",
    contractType: "Indefinido",
  },
  {
    id: "w-6",
    fullName: "Marta Gimenez Soler",
    role: "Coordinador/a",
    email: "m.gimenez@asociacionafda.com",
    phone: "976 443 754",
    workCentre: "Zaragoza - Sta. Lucia",
    status: "activo",
    payrollFolder: "/nominas/2026/mayo/marta-gimenez",
    lastPayslipSent: "5 jun 2026",
    notes: "Coordinacion de equipo terapeutico.",
    startDate: "1 feb 2018",
    contractType: "Indefinido",
  },
  {
    id: "w-7",
    fullName: "Javier Molina Torres",
    role: "Psicologo/a",
    email: "j.molina@asociacionafda.com",
    phone: "612 554 883",
    workCentre: "Zaragoza - Sta. Lucia",
    status: "activo",
    payrollFolder: "/nominas/2026/mayo/javier-molina",
    lastPayslipSent: "5 jun 2026",
    notes: "Saberes compartidos y espacios de socializacion.",
    startDate: "12 nov 2020",
    contractType: "Indefinido",
  },
  {
    id: "w-8",
    fullName: "Ana Belen Torres Ruiz",
    role: "Psicologo/a",
    email: "a.torres@asociacionafda.com",
    phone: "645 778 201",
    workCentre: "Zaragoza - Sta. Lucia",
    status: "activo",
    payrollFolder: "/nominas/2026/mayo/ana-torres",
    lastPayslipSent: "4 jun 2026",
    notes: "Juecharlas y actividades comunitarias.",
    startDate: "8 may 2021",
    contractType: "Indefinido",
  },
  {
    id: "w-9",
    fullName: "Raquel Prieto Navarro",
    role: "Administrativo/a",
    email: "r.prieto@asociacionafda.com",
    phone: "976 443 754",
    workCentre: "Zaragoza - Sta. Lucia",
    status: "activo",
    payrollFolder: "/nominas/2026/mayo/raquel-prieto",
    lastPayslipSent: "5 jun 2026",
    notes: "Gestion administrativa y nominas.",
    startDate: "1 jul 2017",
    contractType: "Indefinido",
  },
  {
    id: "w-10",
    fullName: "Raul Prieto Gomez",
    role: "Fisioterapeuta",
    email: "r.prieto.fisio@asociacionafda.com",
    phone: "633 901 442",
    workCentre: "Huesca - Berenguer",
    status: "activo",
    payrollFolder: "/nominas/2026/mayo/raul-prieto",
    lastPayslipSent: "5 jun 2026",
    notes: "Fisioterapia en sede Huesca.",
    startDate: "15 oct 2022",
    contractType: "Indefinido",
  },
  {
    id: "w-11",
    fullName: "Isabel Romero Diaz",
    role: "Administrativo/a",
    email: "i.romero@asociacionafda.com",
    phone: "691 846 596",
    workCentre: "Huesca - Berenguer",
    status: "activo",
    payrollFolder: "/nominas/2026/mayo/isabel-romero",
    lastPayslipSent: "4 jun 2026",
    notes: "Atencion telefonica y citas.",
    startDate: "2 mar 2019",
    contractType: "Indefinido",
  },
  {
    id: "w-12",
    fullName: "Beatriz Lozano Gil",
    role: "Psicologo/a",
    email: "b.lozano@asociacionafda.com",
    phone: "677 334 551",
    workCentre: "Bulbuente",
    status: "inactivo",
    payrollFolder: "/nominas/2026/mayo/beatriz-lozano",
    lastPayslipSent: "3 may 2026",
    notes: "Baja temporal. Ultima nomina enviada en mayo.",
    startDate: "6 jun 2020",
    contractType: "Indefinido",
  },
  {
    id: "w-13",
    fullName: "Francisco Mena Lopez",
    role: "Otro",
    email: "f.mena@asociacionafda.com",
    phone: "620 118 903",
    workCentre: "Zaragoza - Sta. Lucia",
    status: "activo",
    payrollFolder: "/nominas/2026/mayo/francisco-mena",
    lastPayslipSent: "5 jun 2026",
    notes: "Mantenimiento y apoyo logistico.",
    startDate: "1 ene 2024",
    contractType: "Temporal",
  },
  {
    id: "w-14",
    fullName: "Patricia Vega Soto",
    role: "Neuropsicologo/a",
    email: "p.vega@asociacionafda.com",
    phone: "688 442 117",
    workCentre: "Remoto",
    status: "activo",
    payrollFolder: "/nominas/2026/mayo/patricia-vega",
    lastPayslipSent: null,
    notes: "Colaboracion externa. Revisar carpeta de nomina.",
    startDate: "10 feb 2025",
    contractType: "Colaboracion",
  },
];

export const payrollDocuments: PayrollDocument[] = [
  {
    id: "doc-1",
    fileName: "nomina_mayo_2026_elena_martinez.pdf",
    detectedWorker: "Elena Martinez Lopez",
    workerId: "w-1",
    month: "Mayo",
    year: 2026,
    status: "ready_to_send",
  },
  {
    id: "doc-2",
    fileName: "nomina_mayo_2026_pablo_ruiz.pdf",
    detectedWorker: "Pablo Ruiz Garcia",
    workerId: "w-2",
    month: "Mayo",
    year: 2026,
    status: "matched",
  },
  {
    id: "doc-3",
    fileName: "nomina_mayo_2026_laura_sanchez.pdf",
    detectedWorker: "Laura Sanchez Prieto",
    workerId: "w-3",
    month: "Mayo",
    year: 2026,
    status: "matched",
  },
  {
    id: "doc-4",
    fileName: "nomina_mayo_2026_c_ortega.pdf",
    detectedWorker: "Carmen Ortega Vidal",
    workerId: "w-4",
    month: "Mayo",
    year: 2026,
    status: "needs_review",
  },
  {
    id: "doc-5",
    fileName: "nomina_mayo_2026_desconocido.pdf",
    detectedWorker: null,
    workerId: null,
    month: "Mayo",
    year: 2026,
    status: "missing_worker",
  },
  {
    id: "doc-6",
    fileName: "nomina_mayo_2026_j_molina.pdf",
    detectedWorker: "Javier Molina Torres",
    workerId: "w-7",
    month: "Mayo",
    year: 2026,
    status: "duplicate",
  },
  {
    id: "doc-7",
    fileName: "nomina_mayo_2026_marta_gimenez.pdf",
    detectedWorker: "Marta Gimenez Soler",
    workerId: "w-6",
    month: "Mayo",
    year: 2026,
    status: "ready_to_send",
  },
  {
    id: "doc-8",
    fileName: "nomina_mayo_2026_a_torres.pdf",
    detectedWorker: "Ana Belen Torres Ruiz",
    workerId: "w-8",
    month: "Mayo",
    year: 2026,
    status: "matched",
  },
];

export const sendPayslips: SendPayslipItem[] = [
  {
    id: "send-1",
    workerId: "w-1",
    workerName: "Elena Martinez Lopez",
    email: "e.martinez@asociacionafda.com",
    payslipFile: "nomina_mayo_2026_elena_martinez.pdf",
    month: "Mayo",
    year: 2026,
    status: "ready",
  },
  {
    id: "send-2",
    workerId: "w-2",
    workerName: "Pablo Ruiz Garcia",
    email: "p.ruiz@asociacionafda.com",
    payslipFile: "nomina_mayo_2026_pablo_ruiz.pdf",
    month: "Mayo",
    year: 2026,
    status: "sent",
  },
  {
    id: "send-3",
    workerId: "w-3",
    workerName: "Laura Sanchez Prieto",
    email: "l.sanchez@asociacionafda.com",
    payslipFile: "nomina_mayo_2026_laura_sanchez.pdf",
    month: "Mayo",
    year: 2026,
    status: "sent",
  },
  {
    id: "send-4",
    workerId: "w-4",
    workerName: "Carmen Ortega Vidal",
    email: "c.ortega@asociacionafda.com",
    payslipFile: "nomina_mayo_2026_c_ortega.pdf",
    month: "Mayo",
    year: 2026,
    status: "needs_review",
  },
  {
    id: "send-5",
    workerId: "w-5",
    workerName: "Sofia Herrera Mena",
    email: "",
    payslipFile: "nomina_mayo_2026_sofia_herrera.pdf",
    month: "Mayo",
    year: 2026,
    status: "failed",
  },
  {
    id: "send-6",
    workerId: "w-6",
    workerName: "Marta Gimenez Soler",
    email: "m.gimenez@asociacionafda.com",
    payslipFile: "nomina_mayo_2026_marta_gimenez.pdf",
    month: "Mayo",
    year: 2026,
    status: "ready",
  },
  {
    id: "send-7",
    workerId: "w-7",
    workerName: "Javier Molina Torres",
    email: "j.molina@asociacionafda.com",
    payslipFile: "nomina_mayo_2026_j_molina.pdf",
    month: "Mayo",
    year: 2026,
    status: "pending",
  },
  {
    id: "send-8",
    workerId: "w-8",
    workerName: "Ana Belen Torres Ruiz",
    email: "a.torres@asociacionafda.com",
    payslipFile: "nomina_mayo_2026_a_torres.pdf",
    month: "Mayo",
    year: 2026,
    status: "sent",
  },
];

export const trackingRecords: TrackingRecord[] = workers
  .filter((w) => w.status === "activo")
  .map((worker, index) => {
    const statuses: TrackingRecord["confirmationStatus"][] = [
      "sent",
      "sent",
      "pending",
      "needs_review",
      "failed",
      "sent",
      "uploaded",
      "sent",
      "pending",
      "sent",
      "sent",
      "sent",
      "pending",
    ];
    const status = statuses[index] ?? "pending";
    return {
      id: `track-${worker.id}`,
      workerId: worker.id,
      workerName: worker.fullName,
      role: worker.role,
      month: "Mayo",
      year: 2026,
      payslipUploaded: status !== "pending" || index < 10,
      emailMatched: !!worker.email,
      sentDate:
        status === "sent"
          ? `5 jun 2026`
          : status === "failed" || status === "needs_review"
            ? null
            : null,
      confirmationStatus: status,
      issueNotes:
        !worker.email
          ? "Email no registrado"
          : status === "needs_review"
            ? "Revisar coincidencia de archivo"
            : status === "failed"
              ? "Error al enviar: email invalido"
              : "",
    };
  });

export const payrollSettings: PayrollSettings = {
  payrollMonth: "Mayo",
  payrollYear: 2026,
  defaultSenderEmail: "administracion@asociacionafda.com",
  emailSubject: "Nomina correspondiente a [mes] [ano]",
  emailBody:
    "Hola [nombre], adjuntamos tu nomina correspondiente a [mes] [ano]. Un saludo, AFDA.",
  workerCategories: [
    "Psicologo/a",
    "Neuropsicologo/a",
    "Fisioterapeuta",
    "Nutricionista",
    "Administrativo/a",
    "Coordinador/a",
    "Otro",
  ],
  folderStructure: "/nominas/{ano}/{mes}/{apellido-nombre}/",
};

export const workerPayrollHistory: Record<
  string,
  { month: string; year: number; fileName: string; sentDate: string }[]
> = {
  "w-1": [
    {
      month: "Mayo",
      year: 2026,
      fileName: "nomina_mayo_2026_elena_martinez.pdf",
      sentDate: "5 jun 2026",
    },
    {
      month: "Abril",
      year: 2026,
      fileName: "nomina_abril_2026_elena_martinez.pdf",
      sentDate: "6 may 2026",
    },
  ],
  "w-2": [
    {
      month: "Mayo",
      year: 2026,
      fileName: "nomina_mayo_2026_pablo_ruiz.pdf",
      sentDate: "5 jun 2026",
    },
  ],
};
