import type {
  SalaryStructureRecord,
  SalaryStructureSummary,
} from "./types";

function row(
  partial: Omit<
    SalaryStructureRecord,
    "grossTotal" | "totalDeductions" | "netSalary"
  > & {
    grossTotal?: number;
    totalDeductions?: number;
    netSalary?: number;
  }
): SalaryStructureRecord {
  const grossTotal =
    partial.grossTotal ??
    partial.baseSalary +
      partial.extraPay +
      partial.specificComplement +
      partial.otherComplements;
  const totalDeductions =
    partial.totalDeductions ??
    partial.socialSecurityDeduction +
      partial.irpfDeduction +
      partial.otherDeductions;
  const netSalary = partial.netSalary ?? grossTotal - totalDeductions;
  return {
    ...partial,
    grossTotal,
    totalDeductions,
    netSalary,
  };
}

export const salaryStructureRecords: SalaryStructureRecord[] = [
  row({
    id: "sal-1",
    workerId: "w-1",
    workerName: "Elena Martinez Lopez",
    dniNie: "12345678A",
    professionalCategory: "Psicologo/a",
    month: "Mayo",
    year: 2026,
    workedDays: 22,
    baseSalary: 1850.0,
    extraPay: 308.33,
    specificComplement: 120.0,
    otherComplements: 45.0,
    socialSecurityDeduction: 128.42,
    irpfDeduction: 285.5,
    otherDeductions: 0,
    companyCost: 2784.2,
    payslipFile: "nomina_mayo_2026_elena_martinez.pdf",
    reviewStatus: "reviewed",
    sendStatus: "sent",
    sentDate: "5 jun 2026",
    notes: "Nomina revisada y enviada correctamente.",
  }),
  row({
    id: "sal-2",
    workerId: "w-2",
    workerName: "Pablo Ruiz Garcia",
    dniNie: "23456789B",
    professionalCategory: "Neuropsicologo/a",
    month: "Mayo",
    year: 2026,
    workedDays: 21,
    baseSalary: 2100.0,
    extraPay: 350.0,
    specificComplement: 180.0,
    otherComplements: 60.0,
    socialSecurityDeduction: 149.86,
    irpfDeduction: 342.8,
    otherDeductions: 15.0,
    companyCost: 3210.5,
    payslipFile: "nomina_mayo_2026_pablo_ruiz.pdf",
    reviewStatus: "reviewed",
    sendStatus: "sent",
    sentDate: "5 jun 2026",
    notes: "",
  }),
  row({
    id: "sal-3",
    workerId: "w-3",
    workerName: "Laura Sanchez Prieto",
    dniNie: "34567890C",
    professionalCategory: "Psicologo/a",
    month: "Mayo",
    year: 2026,
    workedDays: 22,
    baseSalary: 1780.0,
    extraPay: 296.67,
    specificComplement: 95.0,
    otherComplements: 30.0,
    socialSecurityDeduction: 122.18,
    irpfDeduction: 268.4,
    otherDeductions: 0,
    companyCost: 2658.3,
    payslipFile: "nomina_mayo_2026_laura_sanchez.pdf",
    reviewStatus: "reviewed",
    sendStatus: "sent",
    sentDate: "4 jun 2026",
    notes: "Sede Huesca.",
  }),
  row({
    id: "sal-4",
    workerId: "w-4",
    workerName: "Carmen Ortega Vidal",
    dniNie: "45678901D",
    professionalCategory: "Nutricionista",
    month: "Mayo",
    year: 2026,
    workedDays: 20,
    baseSalary: 1650.0,
    extraPay: 275.0,
    specificComplement: 80.0,
    otherComplements: 25.0,
    socialSecurityDeduction: 112.45,
    irpfDeduction: 241.2,
    otherDeductions: 0,
    companyCost: 2456.8,
    payslipFile: "nomina_mayo_2026_c_ortega.pdf",
    reviewStatus: "pending_review",
    sendStatus: "needs_review",
    sentDate: null,
    notes: "Revisar complemento especifico antes de enviar.",
  }),
  row({
    id: "sal-5",
    workerId: "w-5",
    workerName: "Sofia Herrera Mena",
    dniNie: "X1234567L",
    professionalCategory: "Fisioterapeuta",
    month: "Mayo",
    year: 2026,
    workedDays: 18,
    baseSalary: 1580.0,
    extraPay: 263.33,
    specificComplement: 70.0,
    otherComplements: 40.0,
    socialSecurityDeduction: 108.92,
    irpfDeduction: 228.6,
    otherDeductions: 0,
    companyCost: 2362.1,
    payslipFile: "nomina_mayo_2026_sofia_herrera.pdf",
    reviewStatus: "in_review",
    sendStatus: "failed",
    sentDate: null,
    notes: "Sin email registrado. Revisar datos de contacto.",
  }),
  row({
    id: "sal-6",
    workerId: "w-6",
    workerName: "Marta Gimenez Soler",
    dniNie: "56789012E",
    professionalCategory: "Coordinador/a",
    month: "Mayo",
    year: 2026,
    workedDays: 22,
    baseSalary: 2200.0,
    extraPay: 366.67,
    specificComplement: 250.0,
    otherComplements: 80.0,
    socialSecurityDeduction: 161.24,
    irpfDeduction: 398.5,
    otherDeductions: 20.0,
    companyCost: 3485.6,
    payslipFile: "nomina_mayo_2026_marta_gimenez.pdf",
    reviewStatus: "reviewed",
    sendStatus: "ready",
    sentDate: null,
    notes: "Lista para envio.",
  }),
  row({
    id: "sal-7",
    workerId: "w-7",
    workerName: "Javier Molina Torres",
    dniNie: "67890123F",
    professionalCategory: "Psicologo/a",
    month: "Mayo",
    year: 2026,
    workedDays: 22,
    baseSalary: 1820.0,
    extraPay: 303.33,
    specificComplement: 110.0,
    otherComplements: 35.0,
    socialSecurityDeduction: 126.1,
    irpfDeduction: 278.9,
    otherDeductions: 0,
    companyCost: 2738.4,
    payslipFile: "nomina_mayo_2026_j_molina.pdf",
    reviewStatus: "reviewed",
    sendStatus: "sent",
    sentDate: "5 jun 2026",
    notes: "",
  }),
  row({
    id: "sal-8",
    workerId: "w-8",
    workerName: "Ana Belen Torres Ruiz",
    dniNie: "78901234G",
    professionalCategory: "Psicologo/a",
    month: "Mayo",
    year: 2026,
    workedDays: 21,
    baseSalary: 1800.0,
    extraPay: 300.0,
    specificComplement: 100.0,
    otherComplements: 30.0,
    socialSecurityDeduction: 124.35,
    irpfDeduction: 272.4,
    otherDeductions: 0,
    companyCost: 2706.2,
    payslipFile: "nomina_mayo_2026_a_torres.pdf",
    reviewStatus: "reviewed",
    sendStatus: "sent",
    sentDate: "4 jun 2026",
    notes: "",
  }),
  row({
    id: "sal-9",
    workerId: "w-9",
    workerName: "Raquel Prieto Navarro",
    dniNie: "89012345H",
    professionalCategory: "Administrativo/a",
    month: "Mayo",
    year: 2026,
    workedDays: 22,
    baseSalary: 1550.0,
    extraPay: 258.33,
    specificComplement: 60.0,
    otherComplements: 20.0,
    socialSecurityDeduction: 105.18,
    irpfDeduction: 218.5,
    otherDeductions: 0,
    companyCost: 2312.0,
    payslipFile: "nomina_mayo_2026_raquel_prieto.pdf",
    reviewStatus: "reviewed",
    sendStatus: "sent",
    sentDate: "5 jun 2026",
    notes: "Administracion y nominas.",
  }),
  row({
    id: "sal-10",
    workerId: "w-10",
    workerName: "Raul Prieto Gomez",
    dniNie: "90123456J",
    professionalCategory: "Fisioterapeuta",
    month: "Mayo",
    year: 2026,
    workedDays: 22,
    baseSalary: 1620.0,
    extraPay: 270.0,
    specificComplement: 75.0,
    otherComplements: 25.0,
    socialSecurityDeduction: 110.82,
    irpfDeduction: 235.6,
    otherDeductions: 0,
    companyCost: 2418.5,
    payslipFile: "nomina_mayo_2026_raul_prieto.pdf",
    reviewStatus: "pending_review",
    sendStatus: "pending",
    sentDate: null,
    notes: "Pendiente validacion sede Huesca.",
  }),
];

export function computeSalarySummary(
  records: SalaryStructureRecord[]
): SalaryStructureSummary {
  return {
    totalGross: records.reduce((sum, r) => sum + r.grossTotal, 0),
    totalNet: records.reduce((sum, r) => sum + r.netSalary, 0),
    totalCompanyCost: records.reduce((sum, r) => sum + r.companyCost, 0),
    payslipsReviewed: records.filter((r) => r.reviewStatus === "reviewed")
      .length,
    payslipsPendingReview: records.filter(
      (r) => r.reviewStatus !== "reviewed"
    ).length,
  };
}
